Feature/make gif option
hochbaum/vampire-survivors-tools pull request #2
Opened 2022-02-20 21:26 UTC by SHA65536

2022-02-20 21:29 UTC, SHA65536 commented
I added a -gif flag for making gifs automatically
Since the naming scheme is so inconstant I needed 2 regexps to cover all the naming schemes.
It still messes up sometimes, and the color palette is weird, for example in lama's gif there's a frame with black background instead of transparent, no idea why.
Uh I didn't mean to merge this into master, maybe you could create a feature branch and i'll merge it into that.
What do ya think? :D

2022-02-21 17:31 UTC, hochbaum requested changes
Thank you for your PR, I highly appreciate it!
I have found a few things I would like to see changed when briefly looking over the code:

2022-02-21 17:31 UTC, hochbaum commented on cmd/vs-ripimages/main.go
> +	gifNameExp1, _ := regexp.Compile(`^(.*)_(\d*)\.png`)
I think `regexp.MustCompile` would be better for this as the error should not be thrown away and I'd panic on error anyways.

2022-02-21 17:31 UTC, hochbaum commented on cmd/vs-ripimages/main.go
> +		if *gifFlag {
I feel like this entire block should be inside of its own function.

2022-02-21 17:31 UTC, hochbaum commented on cmd/vs-ripimages/main.go
> +				if img.Bounds().Dx() > maxGif[gifName].X {
Instead of a comment, a new function with a meaningful name would be a lot better.

2022-02-21 17:31 UTC, hochbaum commented on go.mod
> +	github.com/andybons/gogif v0.0.0-20140526152223-16d573594812 // indirect
I got some dependency errors when checking your PR out, did you check in every change to the `go.mod`?

2022-02-21 19:19 UTC, hochbaum requested changes
Looks nice! I have found a few more smaller things.

2022-02-21 19:19 UTC, hochbaum commented on cmd/vs-ripimages/main.go
> +			image.Point{X: bounds.Dx() - srcBounds.Dx(), Y: bounds.Dy() - srcBounds.Dy()},
You don't need to initialize the `Point` directly. There is a constructor named `images.Pt(X, Y)`.

2022-02-21 19:19 UTC, hochbaum commented on cmd/vs-ripimages/main.go
> +		outGif.Image = append(outGif.Image, img)
I am not sure but this might also be worthy of an own function called `configureGif` or something like that.

2022-02-21 19:19 UTC, hochbaum commented on cmd/vs-ripimages/main.go
> +// Returns imges in order according to their position in the gif
I like the fact you documented this. But a convention is to start the doc comment with the symbol's name, for example: 
```go
// orderImages sorts the images according to their position in the GIF.
func orderImages(images map[string]image.Image) (map[string][]image.Image, error)
```
There is also a typo in `imges`. And maybe `sortImages` would sound a fancier name :)

2022-02-22 08:49 UTC, merged